### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by Grungeby52** [zgojcic/3D_multiview_reg#11]
when I run 3DMatch 
python ./scripts/benchmark_pairwise_registration.py \
		--source ./data/eval_data/ \
		--dataset 3d_match \
		--method RegBlock \
		--model ./pretrained/RegBlock/model_best.pt \
		--only_gt_overlap \

I get the following error
  File "./scripts/benchmark_pairwise_registration.py", line 421, in <module>
    evaluate_registration_performance(eval_data, 
  File "./scripts/benchmark_pairwise_registration.py", line 313, in evaluate_registration_performance
    ext_traj_est, ext_traj_gt = extract_corresponding_trajectors(est_pairs,gt_pairs,est_traj, gt_traj)
  File "/home/san/Desktop/3D_multiview_reg-master/lib/utils.py", line 514, in extract_corresponding_trajectors
    est_pairs = est_pairs[:,0:2]
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

What is problem?

Best Regards

**Comment by zgojcic** [comment]
Is this problem solved now with the other issue about the GT transformation parameters?

**Comment by Grungeby52** [comment]
yes solved the way you said, Thank you...

**Comment by zhairenjie** [comment]
Hello, I also encountered the same index error, I would like to ask how you solved it?

**Comment by HOUYONGKUO** [comment]
I also encountered this problem, how can I solve it?

**Comment by houyongkuo** [comment]
I encountered the same problem when extract_data, how to solve it？

**Comment by houyongkuo** [comment]
> Is this problem solved now with the other issue about the GT transformation parameters?



> yes solved the way you said, Thank you...

I encountered the same problem when extract_data, how to solve it？
