### ISSUE TITLE
GT Trans Parameters

### ISSUE THREAD

**Issue by Grungeby52** [zgojcic/3D_multiview_reg#12]
How can I create GT trans parameters of my own ply files?

**Comment by tolgabirdal** [comment]
Well, you have to run some form of a 3D fusion pipeline to avoid manual registration efforts. For that, I would check 3DMatch, BundleFusion/ElasticFusion papers. I would also recommend looking into the ScanNet paper as this proposes an automated pipeline for scanning environments.

**Comment by Grungeby52** [comment]
I didn't understand what the GT parameters were at first, when I found out that point clouds are related to rotates I solved the problem, Thank You...

**Comment by zgojcic** [comment]
Yes exactly, GT transformation parameters are just relative transformation (3x3 rotation matrix and translation vector) expressed in a 4x4 homogeneous transformation matrix.
