### ISSUE TITLE
Status of this repo

### ISSUE THREAD

**Issue by leinxx** [zgojcic/3D_multiview_reg#2]
Great paper. Is there a plan to publish the code recently? 

Thanks,

Lei

**Comment by guangming123** [comment]
it's a systematic and a perfect solution, hope to open the source code recently!
Thanks

**Comment by zgojcic** [comment]
Dear all, 

we have published the first part of the code (pairwise registration) with the rest following in some days/weeks. We are really sorry for the delay, but we lost parts of the code and had to retrain the models. 

If you have any other questions please open a new issue. 

Best
Zan
